//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuoSoftware.DuoSoftPhone.refResourceMonitoring {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnLineAgent", Namespace="http://schemas.datacontract.org/2004/07/DuoSoftware.DC.ResourceMonitoringService." +
        "Classes")]
    [System.SerializableAttribute()]
    public partial class OnLineAgent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AssignSkillsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AssignedRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallAcceptStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DuoSoftware.DuoSoftPhone.refResourceMonitoring.ConcurrencyDetails[] ConcurrencyInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceURIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtentionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastServedSkillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ModeDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan StateDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentCode {
            get {
                return this.AgentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentCodeField, value) != true)) {
                    this.AgentCodeField = value;
                    this.RaisePropertyChanged("AgentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentFullName {
            get {
                return this.AgentFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentFullNameField, value) != true)) {
                    this.AgentFullNameField = value;
                    this.RaisePropertyChanged("AgentFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentStatus {
            get {
                return this.AgentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentStatusField, value) != true)) {
                    this.AgentStatusField = value;
                    this.RaisePropertyChanged("AgentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AssignSkills {
            get {
                return this.AssignSkillsField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignSkillsField, value) != true)) {
                    this.AssignSkillsField = value;
                    this.RaisePropertyChanged("AssignSkills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AssignedRequest {
            get {
                return this.AssignedRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedRequestField, value) != true)) {
                    this.AssignedRequestField = value;
                    this.RaisePropertyChanged("AssignedRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallAcceptStatus {
            get {
                return this.CallAcceptStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.CallAcceptStatusField, value) != true)) {
                    this.CallAcceptStatusField = value;
                    this.RaisePropertyChanged("CallAcceptStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallStatus {
            get {
                return this.CallStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.CallStatusField, value) != true)) {
                    this.CallStatusField = value;
                    this.RaisePropertyChanged("CallStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.ConcurrencyDetails[] ConcurrencyInfo {
            get {
                return this.ConcurrencyInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConcurrencyInfoField, value) != true)) {
                    this.ConcurrencyInfoField = value;
                    this.RaisePropertyChanged("ConcurrencyInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceURI {
            get {
                return this.DeviceURIField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceURIField, value) != true)) {
                    this.DeviceURIField = value;
                    this.RaisePropertyChanged("DeviceURI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extention {
            get {
                return this.ExtentionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtentionField, value) != true)) {
                    this.ExtentionField = value;
                    this.RaisePropertyChanged("Extention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastServedSkill {
            get {
                return this.LastServedSkillField;
            }
            set {
                if ((object.ReferenceEquals(this.LastServedSkillField, value) != true)) {
                    this.LastServedSkillField = value;
                    this.RaisePropertyChanged("LastServedSkill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeField, value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ModeDuration {
            get {
                return this.ModeDurationField;
            }
            set {
                if ((this.ModeDurationField.Equals(value) != true)) {
                    this.ModeDurationField = value;
                    this.RaisePropertyChanged("ModeDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan StateDuration {
            get {
                return this.StateDurationField;
            }
            set {
                if ((this.StateDurationField.Equals(value) != true)) {
                    this.StateDurationField = value;
                    this.RaisePropertyChanged("StateDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusReason {
            get {
                return this.StatusReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusReasonField, value) != true)) {
                    this.StatusReasonField = value;
                    this.RaisePropertyChanged("StatusReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConcurrencyDetails", Namespace="http://schemas.datacontract.org/2004/07/DuoSoftware.DC.ResourceMonitoringService." +
        "Classes")]
    [System.SerializableAttribute()]
    public partial class ConcurrencyDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssignedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AssignedItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] QueuedItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Assigned {
            get {
                return this.AssignedField;
            }
            set {
                if ((this.AssignedField.Equals(value) != true)) {
                    this.AssignedField = value;
                    this.RaisePropertyChanged("Assigned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AssignedItems {
            get {
                return this.AssignedItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedItemsField, value) != true)) {
                    this.AssignedItemsField = value;
                    this.RaisePropertyChanged("AssignedItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Current {
            get {
                return this.CurrentField;
            }
            set {
                if ((this.CurrentField.Equals(value) != true)) {
                    this.CurrentField = value;
                    this.RaisePropertyChanged("Current");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Max {
            get {
                return this.MaxField;
            }
            set {
                if ((this.MaxField.Equals(value) != true)) {
                    this.MaxField = value;
                    this.RaisePropertyChanged("Max");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] QueuedItems {
            get {
                return this.QueuedItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.QueuedItemsField, value) != true)) {
                    this.QueuedItemsField = value;
                    this.RaisePropertyChanged("QueuedItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestType {
            get {
                return this.RequestTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTypeField, value) != true)) {
                    this.RequestTypeField = value;
                    this.RaisePropertyChanged("RequestType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="refResourceMonitoring.IResourceMonitoring")]
    public interface IResourceMonitoring {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceMonitoring/GetOnlineAgentList", ReplyAction="http://tempuri.org/IResourceMonitoring/GetOnlineAgentListResponse")]
        DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] GetOnlineAgentList(string securityToken);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IResourceMonitoring/GetOnlineAgentList", ReplyAction="http://tempuri.org/IResourceMonitoring/GetOnlineAgentListResponse")]
        System.IAsyncResult BeginGetOnlineAgentList(string securityToken, System.AsyncCallback callback, object asyncState);
        
        DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] EndGetOnlineAgentList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceMonitoring/GetCommunicationFaultedAgentList", ReplyAction="http://tempuri.org/IResourceMonitoring/GetCommunicationFaultedAgentListResponse")]
        DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] GetCommunicationFaultedAgentList(string securityToken);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IResourceMonitoring/GetCommunicationFaultedAgentList", ReplyAction="http://tempuri.org/IResourceMonitoring/GetCommunicationFaultedAgentListResponse")]
        System.IAsyncResult BeginGetCommunicationFaultedAgentList(string securityToken, System.AsyncCallback callback, object asyncState);
        
        DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] EndGetCommunicationFaultedAgentList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceMonitoring/GetOnlineAgentDetail", ReplyAction="http://tempuri.org/IResourceMonitoring/GetOnlineAgentDetailResponse")]
        DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent GetOnlineAgentDetail(string securityToken, string guUserId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IResourceMonitoring/GetOnlineAgentDetail", ReplyAction="http://tempuri.org/IResourceMonitoring/GetOnlineAgentDetailResponse")]
        System.IAsyncResult BeginGetOnlineAgentDetail(string securityToken, string guUserId, System.AsyncCallback callback, object asyncState);
        
        DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent EndGetOnlineAgentDetail(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceMonitoring/GetOnlineIdleAgentList", ReplyAction="http://tempuri.org/IResourceMonitoring/GetOnlineIdleAgentListResponse")]
        DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] GetOnlineIdleAgentList(string securityToken);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IResourceMonitoring/GetOnlineIdleAgentList", ReplyAction="http://tempuri.org/IResourceMonitoring/GetOnlineIdleAgentListResponse")]
        System.IAsyncResult BeginGetOnlineIdleAgentList(string securityToken, System.AsyncCallback callback, object asyncState);
        
        DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] EndGetOnlineIdleAgentList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceMonitoring/ChangeAgentSkills", ReplyAction="http://tempuri.org/IResourceMonitoring/ChangeAgentSkillsResponse")]
        bool ChangeAgentSkills(string securityToken, string guUserId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IResourceMonitoring/ChangeAgentSkills", ReplyAction="http://tempuri.org/IResourceMonitoring/ChangeAgentSkillsResponse")]
        System.IAsyncResult BeginChangeAgentSkills(string securityToken, string guUserId, System.AsyncCallback callback, object asyncState);
        
        bool EndChangeAgentSkills(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceMonitoring/LogoffAgent", ReplyAction="http://tempuri.org/IResourceMonitoring/LogoffAgentResponse")]
        bool LogoffAgent(string securityToken, string guUserId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IResourceMonitoring/LogoffAgent", ReplyAction="http://tempuri.org/IResourceMonitoring/LogoffAgentResponse")]
        System.IAsyncResult BeginLogoffAgent(string securityToken, string guUserId, System.AsyncCallback callback, object asyncState);
        
        bool EndLogoffAgent(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceMonitoring/GetOnlineAgentsBySkills", ReplyAction="http://tempuri.org/IResourceMonitoring/GetOnlineAgentsBySkillsResponse")]
        DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] GetOnlineAgentsBySkills(string securityToken, string[] skillIds);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IResourceMonitoring/GetOnlineAgentsBySkills", ReplyAction="http://tempuri.org/IResourceMonitoring/GetOnlineAgentsBySkillsResponse")]
        System.IAsyncResult BeginGetOnlineAgentsBySkills(string securityToken, string[] skillIds, System.AsyncCallback callback, object asyncState);
        
        DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] EndGetOnlineAgentsBySkills(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResourceMonitoringChannel : DuoSoftware.DuoSoftPhone.refResourceMonitoring.IResourceMonitoring, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOnlineAgentListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOnlineAgentListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCommunicationFaultedAgentListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCommunicationFaultedAgentListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOnlineAgentDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOnlineAgentDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOnlineIdleAgentListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOnlineIdleAgentListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChangeAgentSkillsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ChangeAgentSkillsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogoffAgentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LogoffAgentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOnlineAgentsBySkillsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOnlineAgentsBySkillsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResourceMonitoringClient : System.ServiceModel.ClientBase<DuoSoftware.DuoSoftPhone.refResourceMonitoring.IResourceMonitoring>, DuoSoftware.DuoSoftPhone.refResourceMonitoring.IResourceMonitoring {
        
        private BeginOperationDelegate onBeginGetOnlineAgentListDelegate;
        
        private EndOperationDelegate onEndGetOnlineAgentListDelegate;
        
        private System.Threading.SendOrPostCallback onGetOnlineAgentListCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCommunicationFaultedAgentListDelegate;
        
        private EndOperationDelegate onEndGetCommunicationFaultedAgentListDelegate;
        
        private System.Threading.SendOrPostCallback onGetCommunicationFaultedAgentListCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOnlineAgentDetailDelegate;
        
        private EndOperationDelegate onEndGetOnlineAgentDetailDelegate;
        
        private System.Threading.SendOrPostCallback onGetOnlineAgentDetailCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOnlineIdleAgentListDelegate;
        
        private EndOperationDelegate onEndGetOnlineIdleAgentListDelegate;
        
        private System.Threading.SendOrPostCallback onGetOnlineIdleAgentListCompletedDelegate;
        
        private BeginOperationDelegate onBeginChangeAgentSkillsDelegate;
        
        private EndOperationDelegate onEndChangeAgentSkillsDelegate;
        
        private System.Threading.SendOrPostCallback onChangeAgentSkillsCompletedDelegate;
        
        private BeginOperationDelegate onBeginLogoffAgentDelegate;
        
        private EndOperationDelegate onEndLogoffAgentDelegate;
        
        private System.Threading.SendOrPostCallback onLogoffAgentCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOnlineAgentsBySkillsDelegate;
        
        private EndOperationDelegate onEndGetOnlineAgentsBySkillsDelegate;
        
        private System.Threading.SendOrPostCallback onGetOnlineAgentsBySkillsCompletedDelegate;
        
        public ResourceMonitoringClient() {
        }
        
        public ResourceMonitoringClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResourceMonitoringClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceMonitoringClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceMonitoringClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetOnlineAgentListCompletedEventArgs> GetOnlineAgentListCompleted;
        
        public event System.EventHandler<GetCommunicationFaultedAgentListCompletedEventArgs> GetCommunicationFaultedAgentListCompleted;
        
        public event System.EventHandler<GetOnlineAgentDetailCompletedEventArgs> GetOnlineAgentDetailCompleted;
        
        public event System.EventHandler<GetOnlineIdleAgentListCompletedEventArgs> GetOnlineIdleAgentListCompleted;
        
        public event System.EventHandler<ChangeAgentSkillsCompletedEventArgs> ChangeAgentSkillsCompleted;
        
        public event System.EventHandler<LogoffAgentCompletedEventArgs> LogoffAgentCompleted;
        
        public event System.EventHandler<GetOnlineAgentsBySkillsCompletedEventArgs> GetOnlineAgentsBySkillsCompleted;
        
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] GetOnlineAgentList(string securityToken) {
            return base.Channel.GetOnlineAgentList(securityToken);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetOnlineAgentList(string securityToken, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOnlineAgentList(securityToken, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] EndGetOnlineAgentList(System.IAsyncResult result) {
            return base.Channel.EndGetOnlineAgentList(result);
        }
        
        private System.IAsyncResult OnBeginGetOnlineAgentList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string securityToken = ((string)(inValues[0]));
            return this.BeginGetOnlineAgentList(securityToken, callback, asyncState);
        }
        
        private object[] OnEndGetOnlineAgentList(System.IAsyncResult result) {
            DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] retVal = this.EndGetOnlineAgentList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOnlineAgentListCompleted(object state) {
            if ((this.GetOnlineAgentListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOnlineAgentListCompleted(this, new GetOnlineAgentListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOnlineAgentListAsync(string securityToken) {
            this.GetOnlineAgentListAsync(securityToken, null);
        }
        
        public void GetOnlineAgentListAsync(string securityToken, object userState) {
            if ((this.onBeginGetOnlineAgentListDelegate == null)) {
                this.onBeginGetOnlineAgentListDelegate = new BeginOperationDelegate(this.OnBeginGetOnlineAgentList);
            }
            if ((this.onEndGetOnlineAgentListDelegate == null)) {
                this.onEndGetOnlineAgentListDelegate = new EndOperationDelegate(this.OnEndGetOnlineAgentList);
            }
            if ((this.onGetOnlineAgentListCompletedDelegate == null)) {
                this.onGetOnlineAgentListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOnlineAgentListCompleted);
            }
            base.InvokeAsync(this.onBeginGetOnlineAgentListDelegate, new object[] {
                        securityToken}, this.onEndGetOnlineAgentListDelegate, this.onGetOnlineAgentListCompletedDelegate, userState);
        }
        
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] GetCommunicationFaultedAgentList(string securityToken) {
            return base.Channel.GetCommunicationFaultedAgentList(securityToken);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCommunicationFaultedAgentList(string securityToken, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCommunicationFaultedAgentList(securityToken, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] EndGetCommunicationFaultedAgentList(System.IAsyncResult result) {
            return base.Channel.EndGetCommunicationFaultedAgentList(result);
        }
        
        private System.IAsyncResult OnBeginGetCommunicationFaultedAgentList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string securityToken = ((string)(inValues[0]));
            return this.BeginGetCommunicationFaultedAgentList(securityToken, callback, asyncState);
        }
        
        private object[] OnEndGetCommunicationFaultedAgentList(System.IAsyncResult result) {
            DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] retVal = this.EndGetCommunicationFaultedAgentList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCommunicationFaultedAgentListCompleted(object state) {
            if ((this.GetCommunicationFaultedAgentListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCommunicationFaultedAgentListCompleted(this, new GetCommunicationFaultedAgentListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCommunicationFaultedAgentListAsync(string securityToken) {
            this.GetCommunicationFaultedAgentListAsync(securityToken, null);
        }
        
        public void GetCommunicationFaultedAgentListAsync(string securityToken, object userState) {
            if ((this.onBeginGetCommunicationFaultedAgentListDelegate == null)) {
                this.onBeginGetCommunicationFaultedAgentListDelegate = new BeginOperationDelegate(this.OnBeginGetCommunicationFaultedAgentList);
            }
            if ((this.onEndGetCommunicationFaultedAgentListDelegate == null)) {
                this.onEndGetCommunicationFaultedAgentListDelegate = new EndOperationDelegate(this.OnEndGetCommunicationFaultedAgentList);
            }
            if ((this.onGetCommunicationFaultedAgentListCompletedDelegate == null)) {
                this.onGetCommunicationFaultedAgentListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCommunicationFaultedAgentListCompleted);
            }
            base.InvokeAsync(this.onBeginGetCommunicationFaultedAgentListDelegate, new object[] {
                        securityToken}, this.onEndGetCommunicationFaultedAgentListDelegate, this.onGetCommunicationFaultedAgentListCompletedDelegate, userState);
        }
        
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent GetOnlineAgentDetail(string securityToken, string guUserId) {
            return base.Channel.GetOnlineAgentDetail(securityToken, guUserId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetOnlineAgentDetail(string securityToken, string guUserId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOnlineAgentDetail(securityToken, guUserId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent EndGetOnlineAgentDetail(System.IAsyncResult result) {
            return base.Channel.EndGetOnlineAgentDetail(result);
        }
        
        private System.IAsyncResult OnBeginGetOnlineAgentDetail(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string securityToken = ((string)(inValues[0]));
            string guUserId = ((string)(inValues[1]));
            return this.BeginGetOnlineAgentDetail(securityToken, guUserId, callback, asyncState);
        }
        
        private object[] OnEndGetOnlineAgentDetail(System.IAsyncResult result) {
            DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent retVal = this.EndGetOnlineAgentDetail(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOnlineAgentDetailCompleted(object state) {
            if ((this.GetOnlineAgentDetailCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOnlineAgentDetailCompleted(this, new GetOnlineAgentDetailCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOnlineAgentDetailAsync(string securityToken, string guUserId) {
            this.GetOnlineAgentDetailAsync(securityToken, guUserId, null);
        }
        
        public void GetOnlineAgentDetailAsync(string securityToken, string guUserId, object userState) {
            if ((this.onBeginGetOnlineAgentDetailDelegate == null)) {
                this.onBeginGetOnlineAgentDetailDelegate = new BeginOperationDelegate(this.OnBeginGetOnlineAgentDetail);
            }
            if ((this.onEndGetOnlineAgentDetailDelegate == null)) {
                this.onEndGetOnlineAgentDetailDelegate = new EndOperationDelegate(this.OnEndGetOnlineAgentDetail);
            }
            if ((this.onGetOnlineAgentDetailCompletedDelegate == null)) {
                this.onGetOnlineAgentDetailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOnlineAgentDetailCompleted);
            }
            base.InvokeAsync(this.onBeginGetOnlineAgentDetailDelegate, new object[] {
                        securityToken,
                        guUserId}, this.onEndGetOnlineAgentDetailDelegate, this.onGetOnlineAgentDetailCompletedDelegate, userState);
        }
        
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] GetOnlineIdleAgentList(string securityToken) {
            return base.Channel.GetOnlineIdleAgentList(securityToken);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetOnlineIdleAgentList(string securityToken, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOnlineIdleAgentList(securityToken, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] EndGetOnlineIdleAgentList(System.IAsyncResult result) {
            return base.Channel.EndGetOnlineIdleAgentList(result);
        }
        
        private System.IAsyncResult OnBeginGetOnlineIdleAgentList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string securityToken = ((string)(inValues[0]));
            return this.BeginGetOnlineIdleAgentList(securityToken, callback, asyncState);
        }
        
        private object[] OnEndGetOnlineIdleAgentList(System.IAsyncResult result) {
            DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] retVal = this.EndGetOnlineIdleAgentList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOnlineIdleAgentListCompleted(object state) {
            if ((this.GetOnlineIdleAgentListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOnlineIdleAgentListCompleted(this, new GetOnlineIdleAgentListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOnlineIdleAgentListAsync(string securityToken) {
            this.GetOnlineIdleAgentListAsync(securityToken, null);
        }
        
        public void GetOnlineIdleAgentListAsync(string securityToken, object userState) {
            if ((this.onBeginGetOnlineIdleAgentListDelegate == null)) {
                this.onBeginGetOnlineIdleAgentListDelegate = new BeginOperationDelegate(this.OnBeginGetOnlineIdleAgentList);
            }
            if ((this.onEndGetOnlineIdleAgentListDelegate == null)) {
                this.onEndGetOnlineIdleAgentListDelegate = new EndOperationDelegate(this.OnEndGetOnlineIdleAgentList);
            }
            if ((this.onGetOnlineIdleAgentListCompletedDelegate == null)) {
                this.onGetOnlineIdleAgentListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOnlineIdleAgentListCompleted);
            }
            base.InvokeAsync(this.onBeginGetOnlineIdleAgentListDelegate, new object[] {
                        securityToken}, this.onEndGetOnlineIdleAgentListDelegate, this.onGetOnlineIdleAgentListCompletedDelegate, userState);
        }
        
        public bool ChangeAgentSkills(string securityToken, string guUserId) {
            return base.Channel.ChangeAgentSkills(securityToken, guUserId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginChangeAgentSkills(string securityToken, string guUserId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChangeAgentSkills(securityToken, guUserId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndChangeAgentSkills(System.IAsyncResult result) {
            return base.Channel.EndChangeAgentSkills(result);
        }
        
        private System.IAsyncResult OnBeginChangeAgentSkills(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string securityToken = ((string)(inValues[0]));
            string guUserId = ((string)(inValues[1]));
            return this.BeginChangeAgentSkills(securityToken, guUserId, callback, asyncState);
        }
        
        private object[] OnEndChangeAgentSkills(System.IAsyncResult result) {
            bool retVal = this.EndChangeAgentSkills(result);
            return new object[] {
                    retVal};
        }
        
        private void OnChangeAgentSkillsCompleted(object state) {
            if ((this.ChangeAgentSkillsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChangeAgentSkillsCompleted(this, new ChangeAgentSkillsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChangeAgentSkillsAsync(string securityToken, string guUserId) {
            this.ChangeAgentSkillsAsync(securityToken, guUserId, null);
        }
        
        public void ChangeAgentSkillsAsync(string securityToken, string guUserId, object userState) {
            if ((this.onBeginChangeAgentSkillsDelegate == null)) {
                this.onBeginChangeAgentSkillsDelegate = new BeginOperationDelegate(this.OnBeginChangeAgentSkills);
            }
            if ((this.onEndChangeAgentSkillsDelegate == null)) {
                this.onEndChangeAgentSkillsDelegate = new EndOperationDelegate(this.OnEndChangeAgentSkills);
            }
            if ((this.onChangeAgentSkillsCompletedDelegate == null)) {
                this.onChangeAgentSkillsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChangeAgentSkillsCompleted);
            }
            base.InvokeAsync(this.onBeginChangeAgentSkillsDelegate, new object[] {
                        securityToken,
                        guUserId}, this.onEndChangeAgentSkillsDelegate, this.onChangeAgentSkillsCompletedDelegate, userState);
        }
        
        public bool LogoffAgent(string securityToken, string guUserId) {
            return base.Channel.LogoffAgent(securityToken, guUserId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLogoffAgent(string securityToken, string guUserId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogoffAgent(securityToken, guUserId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndLogoffAgent(System.IAsyncResult result) {
            return base.Channel.EndLogoffAgent(result);
        }
        
        private System.IAsyncResult OnBeginLogoffAgent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string securityToken = ((string)(inValues[0]));
            string guUserId = ((string)(inValues[1]));
            return this.BeginLogoffAgent(securityToken, guUserId, callback, asyncState);
        }
        
        private object[] OnEndLogoffAgent(System.IAsyncResult result) {
            bool retVal = this.EndLogoffAgent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLogoffAgentCompleted(object state) {
            if ((this.LogoffAgentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogoffAgentCompleted(this, new LogoffAgentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogoffAgentAsync(string securityToken, string guUserId) {
            this.LogoffAgentAsync(securityToken, guUserId, null);
        }
        
        public void LogoffAgentAsync(string securityToken, string guUserId, object userState) {
            if ((this.onBeginLogoffAgentDelegate == null)) {
                this.onBeginLogoffAgentDelegate = new BeginOperationDelegate(this.OnBeginLogoffAgent);
            }
            if ((this.onEndLogoffAgentDelegate == null)) {
                this.onEndLogoffAgentDelegate = new EndOperationDelegate(this.OnEndLogoffAgent);
            }
            if ((this.onLogoffAgentCompletedDelegate == null)) {
                this.onLogoffAgentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogoffAgentCompleted);
            }
            base.InvokeAsync(this.onBeginLogoffAgentDelegate, new object[] {
                        securityToken,
                        guUserId}, this.onEndLogoffAgentDelegate, this.onLogoffAgentCompletedDelegate, userState);
        }
        
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] GetOnlineAgentsBySkills(string securityToken, string[] skillIds) {
            return base.Channel.GetOnlineAgentsBySkills(securityToken, skillIds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetOnlineAgentsBySkills(string securityToken, string[] skillIds, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOnlineAgentsBySkills(securityToken, skillIds, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] EndGetOnlineAgentsBySkills(System.IAsyncResult result) {
            return base.Channel.EndGetOnlineAgentsBySkills(result);
        }
        
        private System.IAsyncResult OnBeginGetOnlineAgentsBySkills(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string securityToken = ((string)(inValues[0]));
            string[] skillIds = ((string[])(inValues[1]));
            return this.BeginGetOnlineAgentsBySkills(securityToken, skillIds, callback, asyncState);
        }
        
        private object[] OnEndGetOnlineAgentsBySkills(System.IAsyncResult result) {
            DuoSoftware.DuoSoftPhone.refResourceMonitoring.OnLineAgent[] retVal = this.EndGetOnlineAgentsBySkills(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOnlineAgentsBySkillsCompleted(object state) {
            if ((this.GetOnlineAgentsBySkillsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOnlineAgentsBySkillsCompleted(this, new GetOnlineAgentsBySkillsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOnlineAgentsBySkillsAsync(string securityToken, string[] skillIds) {
            this.GetOnlineAgentsBySkillsAsync(securityToken, skillIds, null);
        }
        
        public void GetOnlineAgentsBySkillsAsync(string securityToken, string[] skillIds, object userState) {
            if ((this.onBeginGetOnlineAgentsBySkillsDelegate == null)) {
                this.onBeginGetOnlineAgentsBySkillsDelegate = new BeginOperationDelegate(this.OnBeginGetOnlineAgentsBySkills);
            }
            if ((this.onEndGetOnlineAgentsBySkillsDelegate == null)) {
                this.onEndGetOnlineAgentsBySkillsDelegate = new EndOperationDelegate(this.OnEndGetOnlineAgentsBySkills);
            }
            if ((this.onGetOnlineAgentsBySkillsCompletedDelegate == null)) {
                this.onGetOnlineAgentsBySkillsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOnlineAgentsBySkillsCompleted);
            }
            base.InvokeAsync(this.onBeginGetOnlineAgentsBySkillsDelegate, new object[] {
                        securityToken,
                        skillIds}, this.onEndGetOnlineAgentsBySkillsDelegate, this.onGetOnlineAgentsBySkillsCompletedDelegate, userState);
        }
    }
}
